spring.main.web-application-type=servlet
server.port=${PORT:8000}

integration.url.monolith=${MONOLITH_URL:http://localhost:8080}
integration.url.movies=${MOVIES_SERVICE_URL:http://localhost:8081}
integration.url.events=${EVENTS_SERVICE_URL:http://localhost:8082}
integration.movies.migration.percent=${MOVIES_MIGRATION_PERCENT:http://localhost:8082}
integration.gradual.migration=${GRADUAL_MIGRATION:true}